baseURL = "https://icci.ink/"
locale = "zh-cn"
title = "ICCI"
theme = "hugo-book-main"

enableRobotsTXT = true
buildDrafts = false
enableEmoji = true
paginate = 8

[services.googleAnalytics]
  id = "G-SXT0DC8SZ7"

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = '*'
  BookDateFormat = '2006-01-02'
  BookSearch = true
  BookLogo = 'images/icci.jpg'
  BookFavicon = 'images/icci.jpg'

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions]
  [markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
      block = [['$$', '$$']]
      inline = [['$', '$']]

[menu]
  [[menu.after]]
    name = "GitHub"
    url = "https://github.com/"
    weight = 10
